name: wikibus-brochures
services:
  appserver:
    type: dotnet
    command: dotnet watch --project src/app run --environment Development
    port: 80
    overrides:
      environment:
        PORT: 80
        authentication__backdoor: "True"
        wikibus__baseUrl: "https://wikibus-sources.lndo.site/"
        wikibus__apiUrl: "https://wikibus-sources.lndo.site/"
        wikibus__sources__sql: "Server=db;Database=master;User=sa;Password=he11oTHERE;"
    run_as_root:
      - bash -c "dotnet run --project src/wikibus.sources.dbup remote --connection-string 'Server=db;Database=master;User=sa;Password=he11oTHERE;' --run-always-pattern fn_"
  db:
    type: mssql
    portforward: false
    creds:
      password: he11oTHERE
proxy:
  appserver:
    - wikibus-sources.lndo.site
tooling:
  dotnet:
    service: appserver
    command: dotnet
