language: node_js
node_js: "13"

services:
  - docker

before_install:
  - sudo apt-get -y update || true
  - sudo apt-get -y install cgroup-bin curl
  - curl -fsSL -o /tmp/lando-latest.deb https://github.com/lando/lando/releases/download/v3.0.0-rc.23/lando-v3.0.0-rc.23.deb
  - sudo dpkg -i /tmp/lando-latest.deb
  - lando version
  - cp -r ~/.lando/certs/lndo.site.pem /usr/local/share/ca-certificates/lndo.site.pem
  - cp -r ~/.lando/certs/lndo.site.crt /usr/local/share/ca-certificates/lndo.site.crt
  - update-ca-certificate

jobs:
  include:
    - env:
        - JOB=analyser
      before_script:
        - lando start
        - npx wait-on --timeout 30000 http://wikibus-sources.lndo.site
      script:
        - docker-compose run analyser
    - env:
        - JOB=e2e
      before_script:
        - lando start
        - npx wait-on --timeout 30000 http://wikibus-sources.lndo.site
      script:
        - docker-compose run e2e-tests

