language: node_js
node_js: "13"

services:
  - docker

before_install:
  - sudo apt-get -y update || true
  - sudo apt-get -y install cgroup-bin curl
  - curl -fsSL -o /tmp/lando-latest.deb https://github.com/lando/lando/releases/download/v3.0.0-rc.23/lando-v3.0.0-rc.23.deb
  - sudo dpkg -i /tmp/lando-latest.deb
  - lando version

jobs:
  include:
    - env:
        - JOB=analyser
      before_script:
        - lando start
        - npx wait-on --timeout 30000 https://wikibus-sources.lndo.site
        - sudo .build/certs.sh
      script:
        - docker-compose run analyser
    - env:
        - JOB=e2e
      before_script:
        - lando start
        - npx wait-on --timeout 30000 https://wikibus-sources.lndo.site
        - sudo .build/certs.sh
      script:
        - docker-compose run e2e-tests

