language: node_js
node_js: "13"

services:
  - docker

before_script:
  - npm -g wait-on
  - docker-compose up sources db -d
  - wait-on --timeout 30000 http://localhost:17900

script:
  - docker-compose run e2e-tests
  - docker-compose run analyser
