language: csharp

before_script:
  - nvm install 13

services:
  - docker

env:
  - APP_NAME=wikibus-functions

jobs:
  include:
    - stage: test
    - name: unit tests
      script:
        - dotnet test
    - name: analyse
      before_script:
        - .travis/lando.sh
      script:
        - docker-compose -f docker-compose.yml -f docker-compose.posix.yml run analyser
    - name: e2e
      before_script:
        - .travis/lando.sh
      script:
        - docker-compose -f docker-compose.yml -f docker-compose.posix.yml run e2e-tests
    - stage: deploy
    - name: staging functions
      if: branch = develop
      before_script:
        - .travis/az-cli.sh
        - az login --service-principal --username "$APP_ID" --password "$PASSWORD" --tenant "$TENANT_ID"
      script:
        - cd src/wikibus.sources.functions/
        - az account get-access-token --query "accessToken" | func azure functionapp publish $APP_NAME --slot staging
    - name: production functions
      if: branch = master
      before_script:
        - .travis/az-cli.sh
        - az login --service-principal --username "$APP_ID" --password "$PASSWORD" --tenant "$TENANT_ID"
      script:
        - cd src/wikibus.sources.functions/
        - az account get-access-token --query "accessToken" | func azure functionapp publish $APP_NAME

