version: "3"
services:
  analyser:
    image: "hydrofoil/hydra-analyser"
    network_mode: "host"
    environment:
      ENTRYPOINT_URL: "https://wikibus-sources.lndo.site/"
  e2e-tests:
    build: e2e-tests
    network_mode: "host"
    environment:
      BASE_URI: "https://wikibus-sources.lndo.site/"
