version: "3"
services:
  analyser:
    image: "hydrofoil/hydra-analyser"
    network_mode: "host"
    environment:
      NODE_EXTRA_CA_CERTS: "/lndo.site.crt"
      ENTRYPOINT_URL: "https://wikibus-sources.lndo.site/"
  e2e-tests:
    image: hydrofoil/hypertest:_0.5.0
    network_mode: "host"
    environment:
      NODE_EXTRA_CA_CERTS: "/lndo.site.crt"
      BASE_URI: "https://wikibus-sources.lndo.site/"
    volumes:
      - ~/.lando/certs/lndo.site.crt:/lndo.site.crt
      - ./e2e-tests:/tests
