name: CI

on:
  push:
    branches:
      - function

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.4.0
      - run: dotnet build src/wikibus.sources.functions.pdf2img --configuration Release
      - uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: wikibus-test-pdf2img
          publish-profile: ${{ secrets.SCM_CREDENTIALS }}
