name: Build & Deploy

on:
  push: 
    branches: '*'
  pull_request:
    branches:
    - master
    - develop

env:
  FUNCTIONS_APP_NAME: wikibus_functions

jobs:
  xunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - run: dotnet test

  analyse:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install lando
        run: sh .ci/install-lando.sh
      - name: Start site
        run: sh .ci/start-lando.sh
      - run: docker-compose -f docker-compose.yml -f docker-compose.posix.yml run analyser

  e2e-tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install lando
        run: sh .ci/install-lando.sh
      - name: Start site
        run: sh .ci/start-lando.sh
      - run: docker-compose -f docker-compose.yml -f docker-compose.posix.yml run e2e-tests

  deploy:
    runs-on: [ubuntu-latest]
    # needs: [xunit, analyse, e2e-tests]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - name: Build
        run: dotnet build src/wikibus.sources.functions -c Release --output ./output
      - name: Deploy staging
        uses: Azure/functions-action@v1.1.3
        if: github.ref == 'refs/heads/develop'
        with:
          app-name: ${{ env.FUNCTIONS_APP_NAME }}
          package: ./output
          slot-name: staging
          publish-profile: ${{ secrets.PUBLISH_FUNCTIONS_STAGING }}
      - name: Deploy production
        uses: Azure/functions-action@v1.1.3
        if: github.ref == 'refs/heads/master'
        with:
          app-name: ${{ env.FUNCTIONS_APP_NAME }}
          package: ./output
          publish-profile: ${{ secrets.PUBLISH_FUNCTIONS }}
